### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by slbayer** [ne3x7/pysymspell#4]
I downloaded this archive and attempted to load the 80K-entry dictionary found here: 

https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell/frequency_dictionary_en_82_765.txt

However, dictionary load took forever on my Mac mini with 16GB of memory running 10.13.5, using Python 2.7 from macports (not sure any of this really matters). The problem that I found is that the code has numerous instances of 

if &lt;key&gt; in &lt;dict&gt;.keys()

rather than

&lt;dict&gt;.has_key(&lt;key&gt;)

I've uploaded an appropriate diff with the current master: 
[symspell.diff.zip](https://github.com/ne3x7/pysymspell/files/2156744/symspell.diff.zip)

**Comment by JerroldJV** [comment]
I'd like to second this issue.  On python 2 <dict>.keys() returns a list, not a set, so the "in" check grows at O(n) instead of O(1).  This makes the load_dictionary grow at O(n^2) to the number of terms, not O(n).  After making the changes suggested above, the example dictionary loads in ~5 seconds instead of not completing after several hours.

**Comment by ne3x7** [comment]
@JerroldJV @slbayer in Python 3 there's no `.has_key()`, it is deprecated for `in` operator. I strongly advise you to try Python 3, it has some cool new features.
